"""add book policy

Revision ID: 1ce17a27cbd5
Revises: 8d04ba6c321c
Create Date: 2024-01-10 14:20:46.872936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce17a27cbd5'
down_revision: Union[str, None] = '8d04ba6c321c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('book_limit_days', sa.Integer(), nullable=False),
    sa.Column('need_user_phone', sa.Boolean(), nullable=False),
    sa.Column('need_confirm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rental_id'], ['rentals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('rentals', 'days_to_book_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('days_to_book_in', sa.INTEGER(), server_default=sa.text('14'), autoincrement=False, nullable=False))
    op.drop_table('polices')
    # ### end Alembic commands ###
