"""added time fields and book days

Revision ID: 8d04ba6c321c
Revises: c284cfa5dd13
Create Date: 2024-01-09 16:35:05.333858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d04ba6c321c"
down_revision: Union[str, None] = "c284cfa5dd13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rentals",
        sa.Column(
            "days_to_book_in",
            sa.Integer(),
            server_default="14",
            nullable=False,
        ),
    )
    op.add_column("schedules", sa.Column("hour_start_temp", sa.Time(), nullable=True))
    op.execute("UPDATE schedules SET hour_start_temp = make_time(hour_start, 0, 0);")
    op.drop_column("schedules", "hour_start")
    op.alter_column(
        "schedules", "hour_start_temp", nullable=False, new_column_name="hour_start"
    )

    op.add_column("schedules", sa.Column("hour_end_temp", sa.Time(), nullable=True))
    op.execute("UPDATE schedules SET hour_end_temp = make_time(hour_end, 0, 0);")
    op.drop_column("schedules", "hour_end")
    op.alter_column(
        "schedules", "hour_end_temp", nullable=False, new_column_name="hour_end"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedules",
        "hour_end",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "schedules",
        "hour_start",
        existing_type=sa.Time(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("rentals", "days_to_book_in")
    # ### end Alembic commands ###
